---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: kube-ops-view
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-ops-view
      sourceRef:
        kind: HelmRepository
        name: kube-ops-view
        namespace: kube-ops-view
  values:
    replicaCount: 2
    
    resources:
      requests:
        cpu: "16m"
        memory: "24Mi"
      limits:
        cpu: "16m"
        memory: "24Mi"
    nodeSelector:
      intent: control-apps
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
