---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-montecarlo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-config/apps/montecarlo/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client